### ISSUE TITLE
Read video from url

### ISSUE THREAD

**Issue by haojia321** [eugeneware/ffprobe#3]
Hi,
I pass video url to ffprobe() to get video info. 
I can get video info for some url, but cannot when using some other url. And there is no error from the call back, no exception. If I put any of these video url to a browser address bar, I can watch those videos.

Could you advice what could be the reason? 
Thanks

**Comment by isaactzab** [comment]
you mean video as blob data uri?

**Comment by haojia321** [comment]
It turned out to be my local issue
